### ISSUE TITLE
Creates ability to copy note to clipboard

### ISSUE THREAD

**Issue by tcoltonpalm** [jzmiller1/NB1#7]
Creates an option to copy note in menu new number 5, and pushes "quit" down to number 6. 

![capture2](https://user-images.githubusercontent.com/32469128/42186563-26fbaa1e-7e1b-11e8-925c-5bd930b5077b.JPG)

This could be useful when sending and receiving not proposals and talking about note proposals.

**Comment by jzmiller1** [comment]
Closed by PR #6
